### ISSUE TITLE
Add ability to position from the right

### ISSUE THREAD

**Issue by christianklemp-imt** [rfunduk/jquery-tourbus#25]
Adding the ability to position the legs from the right would really help out when working on a leg that is showing for something that is floating right.

**Comment by rfunduk** [comment]
Hey! So do you mean just positioning individual legs to the right of its target element? You should already be able to do that via `data-orientation='right'`.

**Comment by christianklemp-imt** [comment]
Hello! I mean that when I have an element, say a button (see below), floating right and I add a leg that is below it, the width of the leg is not wide enough to fit a exit and next button. So then I add a width with `data-width` and the element then goes beyond the parent element and viewport. This is because of the leg being positioned from the left of the viewport. I worked around this by adding a `data-class` that positions from the right of the viewport and lets left be auto.
![image](https://cloud.githubusercontent.com/assets/11542715/17492696/896c3158-5d72-11e6-80cc-cf333aba0f59.png)

**Comment by rfunduk** [comment]
Ah so for that I think you're looking for the `data-align` option. The default is left, but you can set it to `right` and it should use the offset of the right side of the target element for positioning calculations.

**Comment by christianklemp-imt** [comment]
Ahh I completely overlooked that. Thanks!

**Comment by rfunduk** [comment]
No problem! I hope it works for you :)
