### ISSUE TITLE
$.inArray is not a function error

### ISSUE THREAD

**Issue by steffiau** [rfunduk/jquery-tourbus#27]
I'm using jQuery Tourbus and the environment I am developing in has jQuery but does not use '$' as alias. When I include jQuery Tourbus on the page and start the tour, I am getting '$.inArray is not a function' error in the console.

Error thrown on this line
https://github.com/rfunduk/jquery-tourbus/blob/master/dist/jquery-tourbus.js#L587

Adding `	var $ = jQuery` before module.exports fixes the issue.
```javascript
(function() {
//Add here: var $ = jQuery;
  module.exports = {
    dataProp: function(possiblyFalsy, alternative) {
      if (possiblyFalsy === null || typeof possiblyFalsy === 'undefined') {
        return alternative;
      }
      return possiblyFalsy;
    },
    include: function(value, array) {
      return $.inArray(value, array || []) !== -1;
    }
  };
```

**Comment by rfunduk** [comment]
Thanks for the report. You're absolutely right ;)

**Comment by steffiau** [comment]
Awesome, thanks for the quick response and fix!
