### ISSUE TITLE
Data-arrow value seems to be ignored

### ISSUE THREAD

**Issue by wzol** [rfunduk/jquery-tourbus#28]
I'm trying to make simple tour where I must reposition the arrow or else the leg will overflow to the right, out of the body, but no matter what parameter combination I use it is always centered:

`<li data-el=".container" data-highlight="true" data-scroll-to="false" data-orientation="left" data-width="400" data-arrow="40">`

`<li data-el=".container" data-highlight="true" data-scroll-to="false" data-orientation="bottom" data-width="400" data-arrow="10%">`

Am I doing something wrong?

**Comment by rfunduk** [comment]
`data-arrow` only affects... The arrow! :)

If you want to move the actual leg element you're looking for `data-left`/`data-top`

https://ryanfunduk.com/jquery-tourbus/#leg-options

**Comment by wzol** [comment]
Yes, I know that :) The leg element position is working fine, I need to change the arrow to be at `10%` or `40px` but it seems to ignore the setting: the arrow is always at the center.

**Comment by rfunduk** [comment]
Hmm, well, the arrow repositioning is working for me. Here's a screenshot from a tour I recently implemented which has the arrow set to `25%`:

![screen shot 2017-04-07 at 09 17 00](https://cloud.githubusercontent.com/assets/6437/24801656/253f372e-1b73-11e7-9559-b2afc8693fe4.png)

That's with `data-orientation='left'` obviously. Here's another one with `data-orientation='top'` and `data-arrow='90%'`:

![screen shot 2017-04-07 at 09 19 39](https://cloud.githubusercontent.com/assets/6437/24801739/6e4eece8-1b73-11e7-8f59-de77878c0681.png)

**Comment by wzol** [comment]
Here is a simplified version of the problem: [jsfiddle](https://jsfiddle.net/v7ejnjw4/)
Am I missing something?

**Comment by rfunduk** [comment]
The code in the fiddle appears to be working fine for me...

![screen shot 2017-04-07 at 11 04 38](https://cloud.githubusercontent.com/assets/6437/24806200/0e15ccd4-1b82-11e7-8f5e-2f998150fb0c.png)

Looks better at 7% IMO 😉

**Comment by wzol** [comment]
Ok, got it: I just checked: in Firefox it works correctly. I'm on Chrome 57.0.2987.133 (64-bit), Win10. 

![clipboard01](https://cloud.githubusercontent.com/assets/11561358/24806869/84c63ce0-1bb6-11e7-9953-82d9d4e9662e.jpg)

**Comment by rfunduk** [comment]
Hmm... my screenshot is also from Chrome 57, but OSX. I'll dust off my windows box and give it a try.

**Comment by rfunduk** [comment]
Yea workin fine here. Same version (57.0.2987.133):

![capture](https://cloud.githubusercontent.com/assets/6437/24807242/7a61f220-1b85-11e7-8133-d9ce71b74350.PNG)

**Comment by wzol** [comment]
Ok, I owe you a beer... There was a buggy userstyle installed in Stylish which affected every site. Now it is fine here too. *blush*

**Comment by rfunduk** [comment]
Haha oh man, I probably spend half my working life down rabbit holes like that.

Let's me honest - half my off-time, too 😛
