### ISSUE TITLE
Leg positions should be calculated before showing the next step instead of at tour start

### ISSUE THREAD

**Issue by wzol** [rfunduk/jquery-tourbus#29]
It is possible that between steps the layout changes (example because of a user action or CSS media query) but it seems that Tourbus only calculates the positions on start, so if a change happens every position will be wrong after the change. Is it possible to change this behavior?

**Comment by rfunduk** [comment]
By far the more common case is that thing don't change between tour legs, so the default is to avoid the recalculation between legs because it's faster.

It's easy to do what you want though. In either `onLegStart` or `onLegEnd` just call `leg.reposition()`. If you do it in `onLegEnd` you'll need to find the _next_ leg and call `reposition` on that of course, but it means it'll definitely happen before its shown.

https://ryanfunduk.com/jquery-tourbus/#leg-methods

**Comment by wzol** [comment]
Putting `leg.reposition()` into `onLegStart` helped. Thank you. 

I'm still thinking about a way to avoid a leg appear offscreen - like when an item becomes 100% width (example the sidebar goes hidden) because of a layout change and you have used `data-orientation="left"` and the leg's `tourbus-next` link becomes unreachable. I'm working on a responsive site where a simple device orientation change can change the layout, so for me it is quite possible that during the tour the user rotates his device. But maybe this is another story :)

**Comment by rfunduk** [comment]
So yea mobile stuff there's less of a good story for. You can of course call other leg methods to rejigger things. Like for instance you could adjust the tour leg elements and have it refigure everything out. You could even straight up replace the leg dynamically in the tour.

Personally if I need to do special stuff for mobile I detect early and adjust my configuration. You could also have 2 separate tours where you instantiate and start the appropriate one, etc.

Ultimately TourBus isn't all that responsive. It's something of a long running loose end around here and I'm not really sure I want to tackle it in the lib in a generic way.

**Comment by wzol** [comment]
As I feel it is not that far from being responsive. Some features are truly missing, but they don't seem to be impossible:

- reposition legs on layout change (that is already handled with the method you suggested)
- reposition already displayed legs on layout change - this might can be done with binding the window resize event to `leg.reposition()` but I'm not sure if this works with already displayed legs
- per leg option for how to handle legs when the selector is missing/hidden - this might can be done by modifying `onLegStart`, and the possible options could be to show it as a modal or skip, currently as I remember it gives an error to the console and stops
- keep the leg always visible - this could be an override of `data-orientation` if the leg would show offscreen

I think these would cover most of the special cases.

**Comment by rfunduk** [comment]
You definitely should be able to reposition a shown leg. Take a look at the function: https://github.com/rfunduk/jquery-tourbus/blob/master/src/modules/leg.coffee#L45

I recently had a situation where some target elements might not be on the page. And as you said it explodes and errors in that case. So I simply did this:

``` javascript
tourEl.find('li').each ->
  selector = $(this).data('el')
  $(this).remove() if selector && $(selector).length == 0
$.tourbus( tourEl, { ... } )
```

If you had a need to dynamically adjust which elements were in the tour or not... that would be more problematic. You could use the `expose` function to get the `Leg` class and monkeypatch it, I suppose. Or do some other craziness like build the declarative leg elements dynamically...

The leg-always-visible thing, too... I don't have a good answer for that. Again I might suggest (as a short-term fix) to just use `expose` and override the methods you need to behave differently. Make a `_position` method which checks the metrics of the displayed leg and adjust as needed, etc.

**Comment by wzol** [comment]
Wow, I think this is where it has become too advanced for me.  :) What do you think about a solution like this - didn't test it, just an idea:

```
$('#my-tour').tourbus( {
  onLegStart: function( leg, bus ) {
    if( !$(leg.$target).length ) { bus.next(); }
  }
});
```

**Comment by rfunduk** [comment]
Hey sorry I've been MIA, busy around here 👶 

So what you've got there won't work, as you may have already discovered, because of this code: https://github.com/rfunduk/jquery-tourbus/blob/master/src/modules/leg.coffee#L15-L16

You need to handle the problem before the tour initializes.

**Comment by wzol** [comment]
I see. What do you think, is it possible to move this check to render level and just make a skip leg?

**Comment by rfunduk** [comment]
Sure it's possible, but IMO there is no need. It seems to be it would be very uncommon in general to want to have legs that point to target elements that don't exist. So, in the spirit of tourbus being a toolkit to do whatever you want, you can just use that snippet I pasted above. Here's an expanded version in JavaScript:

``` javascript
var tourEl = $('#my-tour')
tourEl.find('li').each( function() {
  var selector = $(this).data('el')
  if( selector && selector.length == 0 ) {
    $(this).remove()
  }
} )
tourEl.tourbus( {
  // options, etc, if needed
} )
```

**Comment by wzol** [comment]
Thanks for the snippet.

In general, you are right, it is not a common situation, but imagine a responsive site, where some elements are hidden/missing because of a smaller client area - for example a sidebar block with recommended articles: it is one of the first things which will be removed on a smaller view. Another example is a hamburger menu: you use two different elements based on client width: with this option the toolkit can handle these cases "out of the box".

**Comment by rfunduk** [comment]
Hm so is the sidebar really not there at all on mobile? Or just hidden?

If it's not there at all, use the same logic you use to skip rendering the sidebar to skip rendering the specific leg in the tour that targets it (or use my snippet above).

If it's just hidden then there's no prob - there won't be an error since the element _does_ exist. You can simply do something like this:

``` javascript
$('#my-tour').tourbus( {
  onLegStart: function( leg, bus ) {
    if( !leg.$target.is(':visible') ) {
      bus.next()
    }
  }
} )
```

:clap: 😊

**Comment by wzol** [comment]
It depends on the site: if it is a heavy sidebar with pictures, gallery, or Facebook iFrame I won't output it, or remove it after output (to free up memory), if it is just some contact info, ads, and related articles I hide it. Things getting a little more complicated, if you have a responsive header too working the same way. So that is why I'm looking for some general solution. :)

**Comment by rfunduk** [comment]
Hm ok fair enough. I still don't really think this is something I want to handle in the library. The whole idea is that it's a bare-bones-ish toolkit that doesn't handle every case everyone ever has. You can accomplish this on a case-by-case basis as-is, and that's the philosophy of this project.

If you regularly need this in your projects, you can write `jquery-tourbus.patch.js` that [uses `expose`](https://ryanfunduk.com/jquery-tourbus/#monkey-patching) to override anything (`Leg` constructor included) to not error on missing target elements. Or you can wrap initialization in a function which goes through the tour elements and removes them as I showed earlier, etc.

**Comment by wzol** [comment]
Ok, I get your point, and yes, there are many special use cases, and handling all of them is not just a big task, but will make the project more complex.
But, I still feel that throwing an exception to the console log, and leaving the page in an intermediate state is not the best way to handle an error.

**Comment by rfunduk** [comment]
It seemed/seems to me that the most probable reason for the target element not existing is that you mistyped the selector, which you'd want to know (forcefully) during development, that's all. Beauty in the eye of the beholder, or something like that 😉
