### ISSUE TITLE
how to set data-el for a dynamically generated element

### ISSUE THREAD

**Issue by shravan1997** [rfunduk/jquery-tourbus#31]
I want to set an element as a leg which will be generated dynamcially as page loads, how to set that element as a data-el element

**Comment by rfunduk** [comment]
If the element the leg _points to_ doesn't exist at the time the tour is initialized you will need to do a bit of hoop jumping and build the leg by hand later.

Leave your leg's `data-el` as blank or just use `body` which is the default. Then use a method to build which gives you the instance, eg:

```
var tour = $.tourbus( '#my-tour-id', {} )
//  or:    $.tourbus( $('#my-tour-id'), {} )
//  or:    $.tourbus( 'build', '#my-tour-id', {} )
```

When your element comes into existence you will need to know the index so you can first set the `data-el` correctly and then [build the leg](https://github.com/rfunduk/jquery-tourbus/blob/master/src/modules/bus.coffee#L52) manually:

```
$(tour.legEls[index]).data( { el: '.selector-which-now-exists' } )
tour.buildLeg( index )
```

Depending on how your tour works there might be a problem with [this line](https://github.com/rfunduk/jquery-tourbus/blob/master/src/modules/bus.coffee#L64) -- you may need to first get the leg at the index and remove it first. Something like:

```
tour.legs[index].destroy()
```

_Disclaimer: This is all from memory as I don't have time to actually try this out at the moment sorry! Hopefully it puts you on the right track._

**Comment by shravan1997** [comment]
Thank you so much, but in my case element don't have I'd and its container
have a class so i need to select that element as queryselectall(. My class
name) [4] like that only

**Comment by rfunduk** [comment]
`data-el` can be any valid jQuery selector.

**Comment by shravan1997** [comment]
There is no selector in my case sir, pardon me let me explain, here I have
a grid which have a class say data-grid-class, and it have 10 elements
horizontal which have same class data - grid-class, I need something like
this qsa('. data-grid-class') [3]

But in this framework I can give only. Data-grid-class

But I need tourleg to be placed in 3rd element of grid which contains that
similar class, but unfortunately id can't be given in my case.

Any help would be appreciated thanks in advance.

**Comment by rfunduk** [comment]
Sure so use a jQuery selector -- `.data-grid-class:nth-child(3)`? Or maybe you're saying you want `.data-grid-class :nth-child(3)`? There's always a way to select any element that exists ;)
