### ISSUE TITLE
Setting TourLeg for dynamically generated element

### ISSUE THREAD

**Issue by shravan1997** [rfunduk/jquery-tourbus#32]
I need to set leg for an element which will be generated dynamically during page load, and it doesnt have any id, it have a common class like .grid1 and there are n elements with that class, how to give that element as data-el , in this case it is not possible to use nth-child to get that element since those elements come in random order.

Any kind of help will be appreciable.

**Comment by rfunduk** [comment]
As I was saying in the other issue, it doesn't matter if it's a dynamically generated element or not, the way the leg targetting works is that it uses jQuery selectors. There is no way to target an element that you can't select via jQuery.
